[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf-extract-kit"
version = "0.1.0"
authors = [
    { name="Bin Wang", email="ictwangbin@gmail.com" }
]
description = "A Comprehensive Toolkit for High-Quality PDF Content Extraction."
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE.md"]
requires-python = ">=3.10"
dependencies = [
    "PyPDF2",
    "matplotlib",
    "pyyaml",
    "frontend",
    "pymupdf",
    "opencv-python>=4.6.0",
    "pyarrow<21.0.0"
]

[project.optional-dependencies]
layout_detection = ["transformers"]
formula_detection = ["ultralytics"]

[tool.setuptools.packages.find]
include = ["pdf_extract_kit*"]
